"""empty message

Revision ID: 9078641abad1
Revises: 5126d24faf30
Create Date: 2023-12-11 09:33:13.955043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9078641abad1'
down_revision: Union[str, None] = '5126d24faf30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('lat', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('lon', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lat', 'lon', name='uq_lat_lon')
    )
    op.create_index('idx_lat_lon', 'spots', ['lat', 'lon'], unique=False)
    op.create_table('users_favorites_spots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('spot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'spot_id', name='uq_user_id_spot_id')
    )
    op.create_index('uq_user_id_spot_id', 'users_favorites_spots', ['user_id', 'spot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_user_id_spot_id', table_name='users_favorites_spots')
    op.drop_table('users_favorites_spots')
    op.drop_index('idx_lat_lon', table_name='spots')
    op.drop_table('spots')
    # ### end Alembic commands ###
