"""empty message

Revision ID: e77e6f485efd
Revises: 9078641abad1
Create Date: 2023-12-12 11:37:42.888521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e77e6f485efd'
down_revision: Union[str, None] = '9078641abad1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_favorites_spots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('spot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'spot_id', name='uq_user_id_spot_id')
    )
    op.drop_index('uq_user_id_spot_id', table_name='users_favorites_spots')
    op.drop_table('users_favorites_spots')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_favorites_spots',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('spot_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'spot_id', name='uq_user_id_spot_id')
    )
    op.create_index('uq_user_id_spot_id', 'users_favorites_spots', ['user_id', 'spot_id'], unique=False)
    op.drop_table('user_favorites_spots')
    # ### end Alembic commands ###
